[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment and edit the line below if you want to change the format
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path before importing the env.py, script.py.mako,
# and migrations files (as well as the requirements file if present).
# If omitted, or empty, the PYTHONPATH is used as usual.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python>=3.6 and the pytz library.
# If omitted, the timezone is taken from the operating system.
# timezone =

# max length of characters to apply to the
# "slug" field
# max_length = 40

# version number padding
# pad_rev_nums = false

# version path separator; As mentioned above, this is the character used to split
# version_locations. The default within new alembic.ini files is "os", which uses
# os.pathsep. If this key is omitted entirely, it falls back to the legacy
# behavior of splitting on spaces and/or commas.
# Valid values for version_path_separator are:
#
# version_path_separator = :
# version_path_separator = ;
# version_path_separator = space
version_path_separator = os

# set to 'true' to search source files recursively
# in each "version_locations" directory
# new in Alembic version 1.10.0
# recursive_version_locations = false

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url =


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are invoked
# automatically by Alembic after it writes a script to the filesystem.
#
# The concept is that the post_write_hook receives the filename of the
# script, along with any command-line arguments, and can modify the file
# or run a command.
#
# The hooks are defined as follows:
#   + <hook name> = <callable>
#   + <hook name>.type = <"console_scripts" | "python">
#   + <hook name>.args = <argument list>
#
# The <hook name> is any name. The ".type" entry is optional and indicates
# how the hook should be executed. If the ".type" entry is omitted, it
# defaults to "python".
#
# For a Python callable, the callable is resolved using the "callable" entry
# and then invoked directly. For a console script, the "callable" entry
# refers to an entrypoint name, which is then resolved using the "console_scripts"
# entrypoint group, and finally executed using subprocess.
#
# Examples:
#
# post_write_hooks = black
# black.type = console_scripts
# black.args = -l 79 REVISION_SCRIPT_FILENAME
#
# post_write_hooks = black
# black.type = python
# black.function = black.reformat